v1.14: ci: fix Windows build (backport of #33467) (#33468)
ci: fix Windows build (#33467)

ci: fix windows build
(cherry picked from commit bdc4cbba4774f77ee7ed3839861cf22aa2b55a0c)

Co-authored-by: Yihau Chen <a122092487@gmail.com>

diff --git a/.github/workflows/release-artifacts.yml b/.github/workflows/release-artifacts.yml
--- a/.github/workflows/release-artifacts.yml
+++ b/.github/workflows/release-artifacts.yml
@@ -48,7 +48,16 @@ jobs:
         shell: bash
         run: |
           choco install openssl
-          export OPENSSL_DIR="C:\Program Files\OpenSSL-Win64"
+          if [[ -d "C:\Program Files\OpenSSL" ]]; then
+            echo "OPENSSL_DIR: C:\Program Files\OpenSSL"
+            export OPENSSL_DIR="C:\Program Files\OpenSSL"
+          elif [[ -d "C:\Program Files\OpenSSL-Win64" ]]; then
+            echo "OPENSSL_DIR: C:\Program Files\OpenSSL-Win64"
+            export OPENSSL_DIR="C:\Program Files\OpenSSL-Win64"
+          else
+            echo "can't determine OPENSSL_DIR"
+            exit 1
+          fi
           choco install protoc
           export PROTOC="C:\ProgramData\chocolatey\lib\protoc\tools\bin\protoc.exe"
           source /tmp/env.sh
